#!/usr/bin/env python3
"""Lip-Sync Studio: a local, sync.so-style app.

    python lipsync-3d/app.py            # then open http://127.0.0.1:7860

1. Drop a video clip (and optionally a new dialogue audio).
2. "Detect faces": faces on the chosen frame get numbered boxes. Pick one -
   or, when the detector finds nothing (stylised 3D faces), click on the
   character's face yourself.
3. "Lip sync": only that face's mouth is regenerated by LatentSync on your
   own GPU, blended back into the untouched frame, and returned with the
   audio. Nothing is uploaded anywhere.

Run it in the LatentSync environment (setup in lipsync-3d/README.md). With
no GPU or no checkpoint pick the "preview" engine: it runs every step except
the model, so the face picking, tracking and blending can be checked.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
YUNET = ROOT / "models" / "yunet.onnx"
RUNS = ROOT / "studio_runs"
DET_LONG = 960                    # detection runs with this long side
LS_FPS = 25                       # LatentSync's own frame rate

ENGINES = {"LatentSync (local GPU)": "latentsync", "Preview (no model)": "preview"}
MODES = {"cut - stop at the shorter of video/audio": "cut",
         "loop - repeat the video to fit the audio": "loop",
         "bounce - play video forward/back to fit the audio": "bounce"}

_PIPE = {}                        # the model, loaded once on first use


# ------------------------------------------------------------- media io

def sh(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError(f"{cmd[0]} failed: {r.stderr.strip()[-600:]}")
    return r.stdout


def probe(path):
    j = json.loads(sh(["ffprobe", "-v", "error", "-show_entries",
                       "stream=codec_type,width,height,r_frame_rate,color_transfer:"
                       "format=duration", "-of", "json", str(path)]))
    v = next((s for s in j["streams"] if s["codec_type"] == "video"), None)
    out = {"duration": float(j["format"].get("duration") or 0),
           "audio": any(s["codec_type"] == "audio" for s in j["streams"])}
    if v:
        n, d = v["r_frame_rate"].split("/")
        out.update(w=int(v["width"]), h=int(v["height"]), rate=f"{n}/{d}",
                   fps=int(n) / int(d), trc=v.get("color_transfer") or "bt709")
    return out


def frames(path, w, h, fmt="rgb24", vf=None):
    """Yield decoded frames one by one; never the whole clip in memory."""
    ch = 3
    args = ["ffmpeg", "-v", "error", "-i", str(path), "-map", "0:v:0",
            "-fps_mode", "passthrough"]
    if vf:
        args += ["-vf", vf]
    # stderr dropped: closing the pipe early (the synced clip is padded
    # longer than needed) makes ffmpeg complain about a broken pipe
    p = subprocess.Popen(args + ["-pix_fmt", fmt, "-f", "rawvideo", "-"],
                         stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    size = w * h * ch
    try:
        while True:
            b = p.stdout.read(size)
            if len(b) < size:
                break
            if fmt == "yuv444p":
                yield np.frombuffer(b, np.uint8).reshape(3, h, w)
            else:
                yield np.frombuffer(b, np.uint8).reshape(h, w, 3)
    finally:
        p.stdout.close()
        p.kill()
        p.wait()


def frame_at(path, t):
    m = probe(path)
    raw = subprocess.run(["ffmpeg", "-v", "error", "-ss", f"{max(t, 0):.3f}",
                          "-i", str(path), "-frames:v", "1", "-pix_fmt", "rgb24",
                          "-f", "rawvideo", "-"], capture_output=True).stdout
    if len(raw) < m["w"] * m["h"] * 3:
        raise RuntimeError("could not read a frame at that time")
    return np.frombuffer(raw[:m["w"] * m["h"] * 3], np.uint8).reshape(m["h"], m["w"], 3)


# ------------------------------------------------------------ detection

class Detector:
    """YuNet at the frame's own aspect ratio. Boxes come back in full-size
    pixels as (x, y, w, h, score)."""

    def __init__(self, w, h, score=0.5):
        if not YUNET.exists():
            raise RuntimeError(f"face model missing: {YUNET} (see README setup)")
        k = DET_LONG / max(w, h)
        self.k = k
        self.size = (int(round(w * k / 2)) * 2, int(round(h * k / 2)) * 2)
        self.net = cv2.FaceDetectorYN.create(str(YUNET), "", self.size, score, 0.3, 5000)

    def __call__(self, rgb):
        small = cv2.resize(rgb, self.size, interpolation=cv2.INTER_AREA)
        _, f = self.net.detect(np.ascontiguousarray(small[:, :, ::-1]))
        if f is None:
            return []
        return sorted(((float(r[0] / self.k), float(r[1] / self.k),
                        float(r[2] / self.k), float(r[3] / self.k), float(r[14]))
                       for r in f), key=lambda b: -b[2] * b[3])


def draw(rgb, faces, pick=None, point=None):
    img = rgb.copy()
    t = max(2, img.shape[0] // 300)
    for i, (x, y, w, h, _) in enumerate(faces):
        col = (0, 220, 90) if pick == i else (255, 200, 0)
        cv2.rectangle(img, (int(x), int(y)), (int(x + w), int(y + h)), col, t)
        cv2.putText(img, str(i + 1), (int(x), int(y) - 8), cv2.FONT_HERSHEY_SIMPLEX,
                    t * .6, col, t)
    if point is not None:
        cv2.drawMarker(img, (int(point[0]), int(point[1])), (255, 40, 40),
                       cv2.MARKER_CROSS, max(20, img.shape[0] // 25), t + 1)
    return img


# ------------------------------------------------------------- pipeline

def prepare(video, audio, mode, dst):
    """The clip the model will see: video timed to the audio per `mode`,
    with that audio. No audio given -> re-sync to the clip's own sound."""
    vm = probe(video)
    src_a = audio or video
    am = probe(src_a)
    if not am["audio"]:
        raise RuntimeError("no audio: upload an audio file or a video that has sound")
    vd, ad = vm["duration"], am["duration"]
    dur = min(vd, ad) if mode == "cut" else ad
    vin = ["-i", str(video)]
    if mode == "bounce" and ad > vd:
        pp = dst.with_name("pingpong.mp4")
        sh(["ffmpeg", "-v", "error", "-i", str(video), "-filter_complex",
            "[0:v]split[a][b];[b]reverse[r];[a][r]concat=n=2:v=1:a=0[v]",
            "-map", "[v]", "-c:v", "libx264", "-crf", "12", "-pix_fmt", "yuv420p",
            "-y", str(pp)])
        vin = ["-stream_loop", "-1", "-i", str(pp)]
    elif mode in ("loop", "bounce") and ad > vd:
        vin = ["-stream_loop", "-1", "-i", str(video)]
    sh(["ffmpeg", "-v", "error", *vin, "-i", str(src_a), "-map", "0:v:0", "-map", "1:a:0",
        "-t", f"{dur:.3f}", "-c:v", "libx264", "-crf", "12", "-preset", "fast",
        "-pix_fmt", "yuv420p", "-r", vm["rate"], "-c:a", "pcm_s16le", "-ar", "48000",
        "-y", str(dst)])
    sh(["ffmpeg", "-v", "error", "-i", str(dst), "-vn", "-ac", "1", "-ar", "16000",
        "-c:a", "pcm_s16le", "-y", str(dst.with_suffix(".wav"))])
    return probe(dst)


def track(clip, m, ref_frame, start_box, score, log):
    """Follow the chosen face through the clip, outward from the frame it
    was picked on. Frames where the detector loses it keep the last box, so
    a stylised face it only sees now and then still gets a usable track.
    Returns one (cx, cy, w, h) per frame."""
    det = Detector(m["w"], m["h"], score)
    found = [det(f) for f in frames(clip, m["w"], m["h"])]
    n = len(found)
    ref = min(max(ref_frame, 0), n - 1)
    out = [None] * n
    hits = 0
    for order in (range(ref, n), range(ref - 1, -1, -1)):
        cur = start_box if order.start == ref else out[ref]
        for i in order:
            cx, cy, w, h = cur
            best = None
            for x, y, fw, fh, _ in found[i]:
                d = np.hypot(x + fw / 2 - cx, y + fh / 2 - cy)
                # it must be near where the face was and of a similar size,
                # or it is another character
                if d < max(w, h) * .6 and .5 < fw / max(w, 1) < 2 \
                        and (best is None or d < best[0]):
                    best = (d, (x + fw / 2, y + fh / 2, fw, fh))
            if best:
                cur = best[1]
                hits += 1
            out[i] = cur
    log(f"tracked the face on {hits}/{n} frames (the rest hold the last position)")
    return out


def crop_box(tr, m, crop_max):
    xs = [t[0] for t in tr]
    ys = [t[1] for t in tr]
    face = max(max(t[2], t[3]) for t in tr)
    side = 2.2 * face + max(max(xs) - min(xs), max(ys) - min(ys))
    side = int(min(max(side, 64), m["w"], m["h"])) // 2 * 2
    x = int(np.clip((max(xs) + min(xs)) / 2 - side / 2, 0, m["w"] - side))
    y = int(np.clip((max(ys) + min(ys)) / 2 - side / 2, 0, m["h"] - side))
    # upscale small crops: LatentSync's detector ignores faces under 50x80 px
    size = int(np.clip(side, 512, crop_max)) // 2 * 2
    return {"x": x, "y": y, "side": side, "size": size}


def run_model(engine, crop_in, wav, crop_out, steps, guidance, seed, ls, log):
    if engine == "preview":
        shutil.copyfile(crop_in, crop_out)
        log("preview engine: mouth left unchanged (no model run)")
        return
    sys.path.insert(0, str(ROOT))
    import latentsync_worker as W
    import torch
    key = (ls["config"], ls["ckpt"])
    if _PIPE.get("key") != key:
        log("loading LatentSync (first run only)...")
        _PIPE.update(key=key, model=W.load(ls["config"], ls["ckpt"], ls["deepcache"]))
    pipe, config, dtype = _PIPE["model"]
    job = {"id": "crop", "video": str(crop_in), "audio": str(wav), "out": str(crop_out),
           "steps": steps, "guidance": guidance, "seed": seed}
    t = time.time()
    try:
        vram = W.run_job(pipe, config, dtype, job, Path("temp_ls_io"))
    except torch.cuda.OutOfMemoryError:
        torch.cuda.empty_cache()
        raise RuntimeError("GPU out of memory. Lower 'Max crop size', use fewer "
                           "steps, or the 256px model (stage2.yaml).")
    except RuntimeError as e:
        if "Face not detected" in str(e):
            raise RuntimeError(
                "LatentSync's own face detector lost the face in some frame. Pick "
                "a frame where the face is clear and frontal, or raise 'Max crop "
                "size' so the face is bigger in the crop.")
        raise
    log(f"LatentSync: {time.time()-t:.0f}s, peak VRAM {vram:.2f} GB")


def blend(clip, m, crop_out, box, tr, dst):
    """Paste only the mouth back. The model's output is level-matched to the
    original over the rest of the crop, so no seam flickers, and every pixel
    outside the mouth ellipse stays the original's. Works in yuv444p: an
    RGB roundtrip shifts the picture's levels."""
    W, H, s = m["w"], m["h"], box["side"]
    x0, y0 = box["x"], box["y"]
    syn = frames(crop_out, s, s, "yuv444p",
                 vf=f"setpts=PTS-STARTPTS,fps={m['rate']},scale={s}:{s}:flags=lanczos,"
                    f"tpad=stop_mode=clone:stop_duration=2")
    trc = {"bt709": 1, "iec61966-2-1": 13, "smpte170m": 6}.get(m["trc"], 1)
    enc = subprocess.Popen(
        ["ffmpeg", "-v", "error", "-f", "rawvideo", "-pix_fmt", "yuv444p",
         "-s", f"{W}x{H}", "-r", m["rate"], "-i", "-", "-i", str(clip),
         "-map", "0:v", "-map", "1:a", "-c:v", "libx264", "-crf", "14",
         "-preset", "medium", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k",
         "-bsf:v", f"h264_metadata=colour_primaries=1:transfer_characteristics={trc}:"
                   f"matrix_coefficients=1:video_full_range_flag=0",
         "-shortest", "-movflags", "+faststart", "-y", str(dst)], stdin=subprocess.PIPE)
    n = 0
    for i, o in enumerate(frames(clip, W, H, "yuv444p")):
        g = next(syn, None)
        out = o.copy()
        if g is not None and i < len(tr):
            cx, cy, fw, fh = tr[i]
            mask = np.zeros((s, s), np.uint8)
            cv2.ellipse(mask, (int(cx - x0), int(cy - y0 + fh * .22)),
                        (int(fw * .42), int(fh * .30)), 0, 0, 360, 255, -1)
            k = int(max(fw, fh) * .12) | 1
            a = cv2.GaussianBlur(mask, (k, k), 0).astype(np.float32) / 255
            rest = a < .02
            for c in range(3):
                oc = o[c, y0:y0 + s, x0:x0 + s].astype(np.float32)
                sc = g[c].astype(np.float32)
                if rest.sum() > 500:
                    sd = sc[rest].std()
                    gain = float(np.clip(oc[rest].std() / sd if sd > 1e-3 else 1, .9, 1.1))
                    sc = sc * gain + (oc[rest].mean() - gain * sc[rest].mean())
                out[c, y0:y0 + s, x0:x0 + s] = np.clip(oc * (1 - a) + sc * a, 0, 255)
        enc.stdin.write(out.tobytes())
        n += 1
    syn.close()
    enc.stdin.close()
    enc.wait()
    if enc.returncode:
        raise RuntimeError("encoding the result failed")
    return n


def lipsync(video, audio, pick, mode, engine, steps, guidance, seed, crop_max,
            score, ls, log=print):
    """pick: {"t": seconds, "box": (cx, cy, w, h)} - the face to sync."""
    run = RUNS / time.strftime("%Y%m%d_%H%M%S")
    run.mkdir(parents=True, exist_ok=True)
    log(f"run folder: {run}")
    clip = run / "input.mp4"
    m = prepare(Path(video), Path(audio) if audio else None, mode, clip)
    log(f"clip: {m['w']}x{m['h']} @ {m['fps']:.3f} fps, {m['duration']:.2f}s")
    tr = track(clip, m, int(round(pick["t"] * m["fps"])), pick["box"], score, log)
    box = crop_box(tr, m, crop_max)
    log(f"speaker crop {box['side']}px at ({box['x']},{box['y']}) -> model at {box['size']}px")
    crop_in, crop_out = run / "crop_in.mp4", run / "crop_out.mp4"
    sh(["ffmpeg", "-v", "error", "-i", str(clip), "-an", "-vf",
        f"crop={box['side']}:{box['side']}:{box['x']}:{box['y']},"
        f"scale={box['size']}:{box['size']}:flags=lanczos,fps={LS_FPS}",
        "-c:v", "libx264", "-crf", "12", "-preset", "fast", "-pix_fmt", "yuv420p",
        "-y", str(crop_in)])
    run_model(engine, crop_in, clip.with_suffix(".wav"), crop_out,
              steps, guidance, seed, ls, log)
    dst = run / "lipsynced.mp4"
    n = blend(clip, m, crop_out, box, tr, dst)
    got = probe(dst)
    log(f"done: {n} frames, {got['duration']:.2f}s -> {dst}")
    (run / "run.json").write_text(json.dumps(
        {"video": str(video), "audio": str(audio) if audio else None, "mode": mode,
         "engine": engine, "steps": steps, "guidance": guidance, "seed": seed,
         "pick": pick, "crop": box}, indent=1))
    return dst


# ------------------------------------------------------------------- ui

def build_ui(ls):
    import gradio as gr

    def detect(video, t, score):
        if not video:
            raise gr.Error("Upload a video first")
        m = probe(video)
        t = min(float(t), max(m["duration"] - 0.05, 0))
        rgb = frame_at(video, t)
        faces = Detector(m["w"], m["h"], score)(rgb)
        st = {"video": video, "t": t, "faces": faces, "pick": 0 if faces else None,
              "point": None, "frame": rgb}
        if faces:
            msg = (f"Found {len(faces)} face(s). Face 1 (largest) is selected - pick "
                   f"another below, or click on the image to choose a face yourself.")
        else:
            msg = ("No face detected on this frame. Click on the character's "
                   "face (between the eyes and the mouth) to mark it, then set "
                   "'Face size' so the green box covers the face.")
        return (draw(rgb, faces, st["pick"]), st,
                gr.update(choices=[f"Face {i+1}" for i in range(len(faces))],
                          value="Face 1" if faces else None), msg)

    def manual_box(st, size_pct):
        h = st["frame"].shape[0] * size_pct / 100
        return (st["point"][0], st["point"][1], h * .8, h)

    def redraw(st, size_pct):
        img = draw(st["frame"], st["faces"], st["pick"], st["point"])
        if st["pick"] is None and st["point"]:
            cx, cy, w, h = manual_box(st, size_pct)
            cv2.rectangle(img, (int(cx - w / 2), int(cy - h / 2)),
                          (int(cx + w / 2), int(cy + h / 2)), (0, 220, 90),
                          max(2, img.shape[0] // 300))
        return img

    def choose(st, which, size_pct):
        if not st or not which:
            return gr.update(), st
        st["pick"], st["point"] = int(which.split()[1]) - 1, None
        return redraw(st, size_pct), st

    def click(st, size_pct, evt: gr.SelectData):
        if not st:
            raise gr.Error("Click 'Detect faces' first")
        x, y = evt.index
        hit = [i for i, (fx, fy, fw, fh, _) in enumerate(st["faces"])
               if fx <= x <= fx + fw and fy <= y <= fy + fh]
        st["pick"], st["point"] = (hit[0], None) if hit else (None, (x, y))
        msg = (f"Face {hit[0]+1} selected." if hit else
               "Manual face position set. Adjust 'Face size' until the green box "
               "covers the face.")
        return redraw(st, size_pct), st, \
            gr.update(value=f"Face {hit[0]+1}" if hit else None), msg

    def resize(st, size_pct):
        return redraw(st, size_pct) if st and st.get("point") else gr.update()

    def go(video, audio, st, size_pct, mode, engine, steps, guidance, seed,
           crop_max, score, progress=gr.Progress()):
        if not video:
            raise gr.Error("Upload a video first")
        if not st or st.get("video") != video:
            raise gr.Error("Click 'Detect faces' and choose the face to sync")
        if st["pick"] is not None:
            x, y, w, h, _ = st["faces"][st["pick"]]
            box = (x + w / 2, y + h / 2, w, h)
        elif st["point"]:
            box = manual_box(st, size_pct)
        else:
            raise gr.Error("Choose a face: pick one from the list or click on the image")
        lines = []

        def log(s):
            lines.append(s)
            progress(min(.95, len(lines) / 8), desc=s[:80])
            print(s, flush=True)

        try:
            out = lipsync(video, audio, {"t": st["t"], "box": box}, MODES[mode],
                          ENGINES[engine], int(steps), float(guidance), int(seed),
                          int(crop_max), float(score), ls, log)
        except Exception as e:
            raise gr.Error(str(e))
        return str(out), "\n".join(lines)

    with gr.Blocks(title="Lip-Sync Studio") as ui:
        gr.Markdown("# Lip-Sync Studio\nLocal lip-sync: your clips never leave "
                    "this machine. **1** upload · **2** detect & pick the face · "
                    "**3** lip sync.")
        st = gr.State()
        with gr.Row():
            with gr.Column():
                video = gr.Video(label="Video clip", sources=["upload"])
                audio = gr.Audio(label="New dialogue audio (optional - empty "
                                 "re-syncs to the clip's own sound)", type="filepath")
                with gr.Row():
                    t = gr.Number(label="Look for faces at (seconds)", value=0.5)
                    score = gr.Slider(0.2, 0.9, 0.5, step=0.05,
                                      label="Detector confidence (lower for "
                                            "cartoon / 3D faces)")
                btn_detect = gr.Button("1. Detect faces", variant="secondary")
            with gr.Column():
                frame = gr.Image(label="Click on a face to choose it",
                                 interactive=False, type="numpy")
                info = gr.Markdown()
                with gr.Row():
                    which = gr.Dropdown(label="Face to sync", choices=[])
                    size_pct = gr.Slider(5, 80, 25, step=1,
                                         label="Face size, % of frame height "
                                               "(manual pick only)")
        with gr.Accordion("Settings", open=False):
            with gr.Row():
                mode = gr.Dropdown(list(MODES), value=list(MODES)[0],
                                   label="When audio and video lengths differ")
                engine = gr.Dropdown(list(ENGINES), value=list(ENGINES)[0],
                                     label="Engine")
            with gr.Row():
                steps = gr.Slider(10, 50, 20, step=1, label="Quality (diffusion steps)")
                guidance = gr.Slider(1.0, 3.0, 1.5, step=0.1,
                                     label="Lip movement strength (guidance)")
                seed = gr.Number(1247, label="Seed", precision=0)
                crop_max = gr.Slider(512, 1536, 768, step=64,
                                     label="Max crop size px (lower = less VRAM)")
        btn_go = gr.Button("2. Lip sync", variant="primary")
        with gr.Row():
            result = gr.Video(label="Lip-synced result")
            logbox = gr.Textbox(label="Log", lines=10)

        btn_detect.click(detect, [video, t, score], [frame, st, which, info])
        which.input(choose, [st, which, size_pct], [frame, st])
        frame.select(click, [st, size_pct], [frame, st, which, info])
        size_pct.change(resize, [st, size_pct], [frame])
        btn_go.click(go, [video, audio, st, size_pct, mode, engine, steps, guidance,
                          seed, crop_max, score], [result, logbox])
    return ui


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=7860)
    ap.add_argument("--ls-config", default="configs/unet/stage2.yaml",
                    help="stage2.yaml = 256px LatentSync 1.5 (~8 GB VRAM); "
                         "stage2_512.yaml = 512px LatentSync 1.6 (~18 GB)")
    ap.add_argument("--ls-ckpt", default="checkpoints/latentsync_unet.pt")
    ap.add_argument("--deepcache", action="store_true",
                    help="faster, slightly lower quality")
    a = ap.parse_args()
    # LatentSync reads configs/ and checkpoints/ relative to the repo root
    os.chdir(REPO)
    ls = {"config": a.ls_config, "ckpt": a.ls_ckpt, "deepcache": a.deepcache}
    # local only: no share link, nothing reachable from outside this machine
    build_ui(ls).queue().launch(server_name="127.0.0.1", server_port=a.port)


if __name__ == "__main__":
    main()
